swagger: "2.0"
info:
  version: 1.0.0
  title: medical-schedule
  description: My cool TypeScript app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ScheduleRule:
    type: object
    title: example
    properties:
      type: number
      startTime: string
      finishTime: string
      rule: string

paths:
  /schedule-rule:
    post:
      tags:
        - Schedule
        - Rule
      description: Create a new Schedule
      parameters:
        - name: schedule
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ScheduleRule"
      responses:
        200:
          description: Returns all examples
    get:
      tags:
        - Schedule
        - Rule
      responses:
        200:
          description: Return the Rules or empty list

  /schedule-rule/{id}:
    delete:
      tags:
        - Schedule
        - Rule
      parameters:
        - name: id
          in: path
          required: true
          description: The id of rule to delete
          type: string
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found
  /schedule:
    get:
      tags:
        - Schedule
      parameters:
        - name: start
          in: query
          required: true
          description: The start date of query
          type: string
        - name: end
          in: query
          required: true
          description: The end date of query
          type: string
      responses:
        200:
          description: Return schedule dates between params
        404:
          description: not found